# Source: card-gateway-runtime/charts/kabang-webservice/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    helm.sh/chart: smalltalk-test-0.1
    app.kabang.io/name: smalltalk
  name: smalltalk-test
  namespace: argocd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list

- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - watch
  - list